### ISSUE TITLE
System.FormatException in head table (E0041)

### ISSUE THREAD

**Issue by wstaelens** [Microsoft/Font-Validator#58]
See attachment.
This is actually an embedded TrueType stream of a Type2CIDFont descendant font of a Type 0 (composite) font in PDF.
The font was extracted with FontForge (that is why you will see the FFTM table).

head table in [Winking](https://www.winking.be) Font Analyzer:
![winking font analyzer](https://user-images.githubusercontent.com/7447285/30206191-95756a40-948b-11e7-9618-30b220b5e35a.PNG)

Microsoft Font Validator:
![validator crash](https://user-images.githubusercontent.com/7447285/30206137-684ccad6-948b-11e7-8b07-e7be722b7d65.PNG)

> System.FormatException: Input string was not in a correct format. at  System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer&  number, NumberFormatInfo info, Boolean parseDecimal) at  System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo  numfmt) at System.Double.Parse(String s, NumberStyles style, NumberFormatInfo  info) at OTFontFileVal.val_head.Validate(Validator v, OTFontVal fontOwner) at  OTFontFileVal.OTFontVal.Validate()

attached font:
[IFOEGC+LucidaGrande-Bold.zip](https://github.com/Microsoft/Font-Validator/files/1287422/IFOEGC.LucidaGrande-Bold.zip) 

link to the source file (line 93 I guess):
https://github.com/Microsoft/Font-Validator/blob/cd1ee1a575c256a1b9497e5e84848650c6e4226f/OTFontFileVal/val_head.cs

**Comment by HinTak** [comment]
What is your expectation for how Font Validator should behave? Extracted font streams from pdf's are, by their own very nature, not well-formed or complete font files. It often just has the minimum amount of information to make pdf work, to keep the pdf file size small.

**Comment by wstaelens** [comment]
With several tools that I test the head table for this font seems ok. also the version number and revision. 
According to the specs, the revision number is Fixed type and defined by the manufacturer.

> Fixed | fontRevision | Set by font manufacturer.

So I don't expect to see some kind of call stack in font validator for that number that seems ok.

I agree that embedded fonts in pdf not always contain all data, but the top part of the head table to me looks valid.
(If not, I would like to learn why not).

**Comment by HinTak** [comment]
I am not keen on find out why it was broken, but it works fine now. Please use v 2.1 from here:
https://github.com/HinTak/Font-Validator/releases
and remember to donate if you find it useful.

This is the output.
[IFOEGC+LucidaGrande-Bold.ttf.report.zip](https://github.com/Microsoft/Font-Validator/files/1293518/IFOEGC.LucidaGrande-Bold.ttf.report.zip)

**Comment by wstaelens** [comment]
Oh I was still using the font validator version 1.0.1286.23890 from the MS typography website... 

v2.1 crashes when validating the font:

Application: FontVal.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.File.InternalDelete(System.String, Boolean)
   at System.IO.File.Delete(System.String)
   at FontVal.Progress.DeleteTemporaryFiles(System.Collections.Generic.List`1<System.String>)
   at FontVal.Progress.OnException(System.Exception)
   at OTFontFileVal.Driver.RunValidation(OTFontFileVal.Validator, System.String[])
   at FontVal.Progress.Worker()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

![font val crash](https://user-images.githubusercontent.com/7447285/30313211-dd685786-979c-11e7-8769-93141f9ba3c7.png)

**Comment by HinTak** [comment]
What locale are you running your computer in? The format.number routine might be sensitive to language issues. But that's a general dotnet runtime issue, not specific to font validator.

**Comment by wstaelens** [comment]
Windows 10 Pro x64 (English)

Control Panel\Clock, Language, and Region\Language:

- Nederlands  (België)
  Keyboard layout: Belgian (Period) (Date, time, and number formatting)

Control Panel\Clock, Language, and Region:

- Region -> Format: Dutch (Belgium)

**Comment by HinTak** [comment]
The version string is "1.0 ", which has an extra space but not unusual.

As for the 2.1 crash message, that's a strange feature of the microsoft code - it deletes the incomplete report whenever anything goes wrong. Unfortunately, when doing so, it can occasionally get confused when one part of it is still holding on while the other tries to delete (on multi-CPU systems); and thus making whatever problem it encounters seems worse. But it is a same issue with number parsing.

I think that's all the information needed. You could try changing to US/UK locale, but it is probably not worth the trouble. You had a good report from me anyway. If anybody else wants to investigate further, please feel free.

(I am just maintaining a "community fork" - has no relationship with microsoft, and do not represent them in any way at all).
